"""Add author

Revision ID: 3ad1b0a5b4e5
Revises: b0f9729b6e26
Create Date: 2024-10-24 11:48:02.134512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad1b0a5b4e5'
down_revision = 'b0f9729b6e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('author', sa.String(), nullable=True))
    op.add_column('sub_questions', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_questions', 'author')
    op.drop_column('questions', 'author')
    # ### end Alembic commands ###
