"""Add analytics

Revision ID: 2c03e0429801
Revises: 317d7db4ab93
Create Date: 2024-10-25 16:20:55.561644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c03e0429801'
down_revision = '317d7db4ab93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'author_edit')
    op.drop_column('analytics', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('analytics', sa.Column('author_edit', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
