"""обновил Question и SubQuestions

Revision ID: e322763f27d3
Revises: 2c1514b19cab
Create Date: 2024-10-01 09:08:43.123164

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e322763f27d3"
down_revision = "2c1514b19cab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("parent_question_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name="fk_questions_category_id"
        ),
        sa.ForeignKeyConstraint(
            ["parent_question_id"],
            ["questions.id"],
            name="fk_questions_parent_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.create_index(
        op.f("ix_questions_text"), "questions", ["text"], unique=False
    )
    op.create_table(
        "sub_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name="fk_subquestions_question_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sub_questions_id"), "sub_questions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sub_questions_text"), "sub_questions", ["text"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_questions_text"), table_name="sub_questions")
    op.drop_index(op.f("ix_sub_questions_id"), table_name="sub_questions")
    op.drop_table("sub_questions")
    op.drop_index(op.f("ix_questions_text"), table_name="questions")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
