"""emove lastname from sers

Revision ID: 02f4a7b69ebb
Revises: ee244d678252
Create Date: 2024-09-13 15:09:10.219377

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02f4a7b69ebb"
down_revision = "ee244d678252"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lastname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "lastname", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
