"""update roles Users

Revision ID: af22f053a663
Revises: 8abf96aa16c0
Create Date: 2024-08-30 09:58:50.021066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af22f053a663"
down_revision = "8abf96aa16c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
