"""обновил SubQuestion изменил question_id на parent_question_id

Revision ID: caf8273f771d
Revises: 2a5529c73262
Create Date: 2024-10-01 10:23:00.527336

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "caf8273f771d"
down_revision = "2a5529c73262"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_questions_subcategory_id", "questions", type_="foreignkey"
    )
    op.drop_column("questions", "subcategory_id")
    op.add_column(
        "sub_questions",
        sa.Column("parent_question_id", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "fk_subquestions_question_id", "sub_questions", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_subquestions_question_id",
        "sub_questions",
        "questions",
        ["parent_question_id"],
        ["id"],
    )
    op.drop_column("sub_questions", "question_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sub_questions",
        sa.Column(
            "question_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        "fk_subquestions_question_id", "sub_questions", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_subquestions_question_id",
        "sub_questions",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.drop_column("sub_questions", "parent_question_id")
    op.add_column(
        "questions",
        sa.Column(
            "subcategory_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "fk_questions_subcategory_id",
        "questions",
        "categories",
        ["subcategory_id"],
        ["id"],
    )
    # ### end Alembic commands ###
