"""Add subquestion in analytics

Revision ID: af51c3545591
Revises: 2c03e0429801
Create Date: 2024-10-28 10:26:39.871984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af51c3545591'
down_revision = '2c03e0429801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('subquestion_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'subquestion_id')
    # ### end Alembic commands ###
