"""обновил Question добавил глубину

Revision ID: 2a5529c73262
Revises: 9ce1eea5d8c9
Create Date: 2024-10-01 10:06:54.083076

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a5529c73262"
down_revision = "9ce1eea5d8c9"
branch_labels = None
depends_on = None


def upgrade():
    # Шаг 1: Добавляем столбец без ограничения NOT NULL
    op.add_column(
        'questions',
        sa.Column('depth', sa.Integer(), nullable=True)
    )

    # Шаг 2: Устанавливаем значение по умолчанию для всех существующих записей
    op.execute('UPDATE questions SET depth = 0 WHERE parent_question_id IS NULL')
    op.execute('UPDATE questions SET depth = 1 WHERE parent_question_id IS NOT NULL')

    # Шаг 3: Изменяем столбец, чтобы сделать его NOT NULL
    op.alter_column('questions', 'depth', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "subcategory_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "fk_questions_subcategory_id",
        "questions",
        "categories",
        ["subcategory_id"],
        ["id"],
    )
    op.drop_column("questions", "depth")
    # ### end Alembic commands ###
