"""обновил Question и SubQuestions

Revision ID: 3c048ace1578
Revises: 9119612399ba
Create Date: 2024-09-30 13:42:52.200891

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c048ace1578"
down_revision = "9119612399ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
