"""Обновление моделей Ordering: Number при создании берет число от ID

Revision ID: c6a38b27d063
Revises: 936702577419
Create Date: 2024-09-17 12:01:07.439486

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6a38b27d063"
down_revision = "936702577419"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
