"""update question

Revision ID: 20c3165e94d2
Revises: 02f4a7b69ebb
Create Date: 2024-09-13 15:36:34.231431

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20c3165e94d2"
down_revision = "02f4a7b69ebb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
