"""обновил Question и SubQuestions

Revision ID: 9ce1eea5d8c9
Revises: e322763f27d3
Create Date: 2024-10-01 09:21:52.613078

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ce1eea5d8c9"
down_revision = "e322763f27d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("subcategory_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_questions_subcategory_id",
        "questions",
        "categories",
        ["subcategory_id"],
        ["id"],
    )
    op.add_column(
        "sub_questions",
        sa.Column("parent_subquestion_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_subquestions_parent_subquestion_id",
        "sub_questions",
        "sub_questions",
        ["parent_subquestion_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subquestions_parent_subquestion_id",
        "sub_questions",
        type_="foreignkey",
    )
    op.drop_column("sub_questions", "parent_subquestion_id")
    op.drop_constraint(
        "fk_questions_subcategory_id", "questions", type_="foreignkey"
    )
    op.drop_column("questions", "subcategory_id")
    # ### end Alembic commands ###
