"""обновил Question и SubQuestions

Revision ID: 9119612399ba
Revises: 7079f16c549a
Create Date: 2024-09-30 13:31:53.914718

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9119612399ba"
down_revision = "7079f16c549a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("subcategory_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_questions_subcategory_id",
        "questions",
        "categories",
        ["subcategory_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_questions_subcategory_id", "questions", type_="foreignkey"
    )
    op.drop_column("questions", "subcategory_id")
    # ### end Alembic commands ###
