"""Add fts

Revision ID: 2ab5c2232b9a
Revises: af51c3545591
Create Date: 2024-10-28 15:30:58.921394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ab5c2232b9a'
down_revision = 'af51c3545591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tsv_content', postgresql.TSVECTOR(), nullable=True))
    op.drop_index('idx_questions_search_vector', table_name='questions', postgresql_using='gin')
    op.create_index('ix_questions_tsv_content', 'questions', ['tsv_content'], unique=False, postgresql_using='gin')
    op.drop_column('questions', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.drop_index('ix_questions_tsv_content', table_name='questions', postgresql_using='gin')
    op.create_index('idx_questions_search_vector', 'questions', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('questions', 'tsv_content')
    # ### end Alembic commands ###
