"""Пересоздание бд

Revision ID: 764304404858
Revises: b4e59993b8c7
Create Date: 2024-10-22 12:46:32.158446

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "764304404858"
down_revision = "b4e59993b8c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sub_questions",
        sa.Column("parent_subquestion_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_subquestions_parent_subquestion_id",
        "sub_questions",
        "sub_questions",
        ["parent_subquestion_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subquestions_parent_subquestion_id",
        "sub_questions",
        type_="foreignkey",
    )
    op.drop_column("sub_questions", "parent_subquestion_id")
    # ### end Alembic commands ###
