"""Add time create and update

Revision ID: 1dcfdcaa151f
Revises: 3ad1b0a5b4e5
Create Date: 2024-10-24 12:41:14.850493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcfdcaa151f'
down_revision = '3ad1b0a5b4e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sub_questions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sub_questions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_questions', 'updated_at')
    op.drop_column('sub_questions', 'created_at')
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###
