"""Add analytics

Revision ID: f837fb167656
Revises: d2082408e9ef
Create Date: 2024-10-25 16:09:57.792259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f837fb167656'
down_revision = 'd2082408e9ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
