"""Обновление категории

Revision ID: c4ef3a4acd0e
Revises: 221898742674
Create Date: 2024-09-20 09:48:51.744897

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c4ef3a4acd0e"
down_revision = "221898742674"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_categories_name", table_name="categories")
    op.create_index(
        op.f("ix_categories_name"), "categories", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index("ix_categories_name", "categories", ["name"], unique=True)
    # ### end Alembic commands ###
