"""Обновление моделей

Revision ID: 31061b0362ad
Revises: c6a38b27d063
Create Date: 2024-09-17 14:11:20.664507

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31061b0362ad"
down_revision = "c6a38b27d063"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("answer", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "answer")
    # ### end Alembic commands ###
