"""Обновление моделей Ordering: Number при создании берет число от ID

Revision ID: 936702577419
Revises: 46b21890dc2f
Create Date: 2024-09-17 11:57:45.276758

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "936702577419"
down_revision = "46b21890dc2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "questions", sa.Column("number", sa.Integer(), nullable=True)
    )
    op.drop_column("questions", "answer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("answer", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("questions", "number")
    op.drop_column("categories", "number")
    # ### end Alembic commands ###
